#!/bin/bash
set -e

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "==> Installing dotfiles from $DOTFILES_DIR"

# ---------------------------------------------------------------------------
# 1. Install editors (Neovim + Helix)
# ---------------------------------------------------------------------------
install_editors() {
    if command -v nvim &>/dev/null && command -v hx &>/dev/null; then
        echo "==> Neovim and Helix already installed, skipping"
        return
    fi

    echo "==> Installing Neovim and Helix..."

    local bin_dir="$HOME/.local/bin"
    mkdir -p "$bin_dir"

    if command -v brew &>/dev/null; then
        command -v nvim &>/dev/null || brew install neovim
        command -v hx &>/dev/null || brew install helix
    else
        # Linux — download prebuilt binaries from GitHub releases (works on any distro)
        local raw_arch
        raw_arch="$(uname -m)"

        # Neovim uses "arm64" while uname reports "aarch64"
        local nvim_arch="$raw_arch"
        case "$raw_arch" in
            aarch64) nvim_arch="arm64" ;;
        esac

        # Neovim
        if ! command -v nvim &>/dev/null; then
            echo "    Downloading Neovim (arch: $nvim_arch)..."
            local nvim_url="https://github.com/neovim/neovim/releases/download/stable/nvim-linux-${nvim_arch}.tar.gz"
            curl -fsSL "$nvim_url" | tar xz -C /tmp
            cp -r /tmp/nvim-linux-${nvim_arch}/* "$HOME/.local/"
            rm -rf /tmp/nvim-linux-${nvim_arch}
            echo "    Neovim installed to $bin_dir/nvim"
        fi

        # Helix — uses aarch64/x86_64 directly
        if ! command -v hx &>/dev/null; then
            echo "    Downloading Helix (arch: $raw_arch)..."
            local hx_tag
            hx_tag="$(curl -fsSL https://api.github.com/repos/helix-editor/helix/releases/latest | grep -oP '"tag_name":\s*"\K[^"]+')"
            local hx_version="${hx_tag}"
            local hx_url="https://github.com/helix-editor/helix/releases/download/${hx_tag}/helix-${hx_version}-${raw_arch}-linux.tar.xz"
            curl -fsSL "$hx_url" | tar xJ -C /tmp
            cp /tmp/helix-${hx_version}-${raw_arch}-linux/hx "$bin_dir/"
            mkdir -p "$HOME/.local/lib"
            cp -r /tmp/helix-${hx_version}-${raw_arch}-linux/runtime "$HOME/.local/lib/helix-runtime" 2>/dev/null || true
            export HELIX_RUNTIME="$HOME/.local/lib/helix-runtime"
            rm -rf /tmp/helix-${hx_version}-${raw_arch}-linux
            echo "    Helix installed to $bin_dir/hx"
        fi
    fi
}

# ---------------------------------------------------------------------------
# 2. Install lazygit
# ---------------------------------------------------------------------------
install_lazygit() {
    if command -v lazygit &>/dev/null; then
        echo "==> lazygit already installed, skipping"
        return
    fi

    echo "==> Installing lazygit..."

    if command -v brew &>/dev/null; then
        brew install lazygit
    else
        local raw_arch
        raw_arch="$(uname -m)"
        local lg_arch="$raw_arch"
        case "$raw_arch" in
            aarch64) lg_arch="arm64" ;;
            x86_64)  lg_arch="x86_64" ;;
        esac

        local lg_tag
        lg_tag="$(curl -fsSL https://api.github.com/repos/jesseduffield/lazygit/releases/latest | grep -oP '"tag_name":\s*"\K[^"]+')"
        local lg_version="${lg_tag#v}"
        local lg_url="https://github.com/jesseduffield/lazygit/releases/download/${lg_tag}/lazygit_${lg_version}_Linux_${lg_arch}.tar.gz"

        local bin_dir="$HOME/.local/bin"
        mkdir -p "$bin_dir"
        curl -fsSL "$lg_url" | tar xz -C /tmp lazygit
        mv /tmp/lazygit "$bin_dir/"
        echo "    lazygit installed to $bin_dir/lazygit"
    fi
}

# ---------------------------------------------------------------------------
# 3. Install language servers (for Helix LSP integration)
# ---------------------------------------------------------------------------
install_language_servers() {
    if ! command -v npm &>/dev/null; then
        echo "==> npm not found, skipping language server installation"
        return
    fi

    echo "==> Installing language servers..."

    local packages=(
        "@vue/typescript-plugin@2"
        "typescript-language-server"
        "typescript"
        "prettier"
    )

    npm install -g "${packages[@]}" 2>/dev/null
    echo "    Language servers installed"

    # Generate Helix languages.toml with correct absolute paths
    generate_helix_languages
}

generate_helix_languages() {
    local npm_root
    npm_root="$(npm root -g)"
    local plugin_path="$npm_root/@vue/typescript-plugin"

    if [ ! -d "$plugin_path" ]; then
        echo "    WARNING: @vue/typescript-plugin not found at $plugin_path"
        return
    fi

    echo "    Generating Helix languages.toml (plugin: $plugin_path)"
    cat > "$DOTFILES_DIR/config/helix/languages.toml" <<TOML
# Auto-generated by install.sh — do not edit manually
# Plugin path: $plugin_path

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "$plugin_path"
languages = ["vue"]

# ─── Languages ───────────────────────────────────────────────────────────────

[[language]]
name = "vue"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "vue"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "babel"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--parser", "scss"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true
TOML
}

# ---------------------------------------------------------------------------
# 4. Symlink config directories
# ---------------------------------------------------------------------------
link_config() {
    local src="$1" dst="$2"
    if [ -e "$dst" ] || [ -L "$dst" ]; then
        echo "    Backing up existing $dst -> ${dst}.bak"
        mv "$dst" "${dst}.bak"
    fi
    mkdir -p "$(dirname "$dst")"
    ln -sf "$src" "$dst"
    echo "    Linked $src -> $dst"
}

setup_configs() {
    echo "==> Linking config files..."
    link_config "$DOTFILES_DIR/config/nvim"  "$HOME/.config/nvim"
    link_config "$DOTFILES_DIR/config/helix" "$HOME/.config/helix"

    if [[ "$(uname)" == "Darwin" ]]; then
        link_config "$DOTFILES_DIR/config/lazygit" "$HOME/Library/Application Support/lazygit"
    else
        link_config "$DOTFILES_DIR/config/lazygit" "$HOME/.config/lazygit"
    fi
}

# ---------------------------------------------------------------------------
# 5. Shell setup
# ---------------------------------------------------------------------------
setup_shell() {
    echo "==> Setting up shell aliases..."
    local marker="# >>> dotfiles <<<"
    local rc="$HOME/.zshrc"

    # Create .zshrc if it doesn't exist
    touch "$rc"

    # Only append if not already sourced
    if ! grep -qF "$marker" "$rc" 2>/dev/null; then
        cat >> "$rc" <<EOF

$marker
[ -f "$DOTFILES_DIR/shell/aliases.sh" ] && source "$DOTFILES_DIR/shell/aliases.sh"
# Source local secrets (not tracked by git)
[ -f "\$HOME/.zshrc.local" ] && source "\$HOME/.zshrc.local"
# <<< dotfiles >>>
EOF
        echo "    Added dotfiles source block to $rc"
    else
        echo "    Shell already configured, skipping"
    fi
}

# ---------------------------------------------------------------------------
# 6. Git config (includes, so it layers on top of existing config)
# ---------------------------------------------------------------------------
setup_git() {
    echo "==> Setting up git config..."
    git config --global include.path "$DOTFILES_DIR/git/gitconfig"
    echo "    Added git include for $DOTFILES_DIR/git/gitconfig"
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------
install_editors
install_lazygit
install_language_servers
setup_configs
setup_shell
setup_git

echo "==> Dotfiles installed successfully!"
